#+STARTUP: showall indent
#+STARTUP: hidestars
#+TITLE: Expected Value of a Continuous Uniform Distribution
#+OPTIONS: ^:nil, TeX:nil
#+AUTHOR: Warren Wilkinson
#+BEGIN_HTML
---
layout: default
title: Expected Value of a Continuous Uniform Distribution
excerpt: And also, first post.
categories:
    - emacs
    - statistics
---
#+END_HTML


* Inputting Greek Characters

I've been told that the variance of a continuous uniform distribution is something.
Now I want to prove it; and learn more about emacs.

So first... variance..

#+begin_src emacs
M-x set-input-method RET TeX
#+end_src

Now I can write \sigma^2 to produce σ². Which is the variance, go me.

However, I notice when I export, ''\sigma^2' gets converted to σ². I don't
want that, because I'm writing the greek symbols directly as UTF8 in my file, 
so I turn that off with

 : #+OPTIONS: ^:nil, TeX:nil

Now, I'm pretty happy, but it's a bit annoying that my input mode bothers
me each time I type a \, -, ^, or _.   Luckily I can press C-\ to turn
it off and on.  I'm happy.

(Later, I found that if I'd let Org mode do the conversion, I could inline 
x_{max} and have it expanded. There are no greek letters for tiny m-a-x, so my
method is inferior).

* Inputting Formulas

Can I write the formula? MathML or something?  I can use:

#+BEGIN_EXAMPLE
\begin{equation}
x=\sqrt{b}
\end{equation}
#+END_EXAMPLE

And I get:

\begin{equation}
x=\sqrt{b}
\end{equation}

Again, happy.

* Density Function and Probability

Okay, here is what my book tells me:

In a uniform distribution, x has a density function

\begin{equation}
f(x) = \frac{1}{x_{max} - x_{min}}
\end{equation}

So what's x? I guess the domain. Fine. So lets pretend
we've got a machine that randomly picks points on the line
between (3,0) and (5,0).  X would be between 3 and 5.

So the probability of the point being between points a and b is:

\begin{equation}
P_{ab} = \frac{(b -a)}{(x_{max} - x_{min})}
\end{equation}
of an region along that line.

It's pretty easy to compute: Basically take the sum of 
the probabilities of all the points between A and B. In
a continuous situation, that's an integral.

\begin{equation}
P_{ab} = \int_a^b f(x) \mathrm{d} x = \int_a^b \frac{1}{x_{max} - x_{min}} \mathrm{d}x
\end{equation}

Notice that f(x) is actually a constant that doesn't depend on x at all...

\begin{equation}
P_{ab} = \frac{1}{x_{max} - x_{min}} \int_a^b 1 \mathrm{d}x
\end{equation}

\begin{equation}
P_{ab} = \frac{1}{x_{max} - x_{min}}\Bigg [_a^b x
\end{equation}


\begin{equation}
P_{ab} = \frac{b -a}{x_{max} - x_{min}}
\end{equation}

Wow, I made several mistakes writing out the LaTeX for that.  I know org mode can preview those equations (as images) as I write them.
I'll learn how to turn that on, next time, so I can minimize the number of typing->output trips I need to make.

Okay, that's the easy stuff.

*  Expected Value

So, the expected value E(x) = μ is the mean (the symbols represent the
same thing).  In other words -- if we randomly picked a hundred
thousand billion numbers, and averaged them all together, what would
we expect the result to be.

Since I'm a big fan of actually trying things, lets do that.

#+begin_src elisp
  ;; Put cursor on closing paren and
  ;; press C-x C-e to evaluate
  
  (defvar *x-min* 3.0)
  (defvar *x-max* 5.0)
  
  ;; Emacs doesn't have random floating
  ;; point numbers. So approximate it 
  ;;...
  
  ;(defun pick-number ()
  ;  (+ (random (- *x-max* *x-min*)) *x-min*))
  
  (defun pick-number ()
    (+ (/ (random (* (floor (- *x-max* *x-min*)) 1000000)) 1000000.0) *x-min*))
  
  ;; Use C-u C-x C-e to evaluate and print results
  
  (pick-number)3.053389
  (pick-number)4.5719829999999995
  (pick-number)3.5274710000000002
  
  (defun take-average (n)
    (let ((accumulator 0))
      (dotimes (x n (/ accumulator n))
        (incf accumulator (pick-number)))))
  
  (take-average 100)3.9764163599999995
  (take-average 1000)3.9871245689999983)
  (take-average 10000)4.003674864100012

#+end_src

Wild guess: E(x) = 4.    

Anyway, a better way would be to actually take a weighted average of all
the probabilities. 

\begin{equation}
E(x) = \int_3^5 xf(x) \mathrm{d}x = \ldots
\end{equation}

And once again f(x) is actually a constant that doesn't depend on x at all
(*but that won't be true of other distributions!!!*), so we'll just call it
C.

\begin{equation}
C = \frac{1}{5-3} = \frac{1}{2}
\end{equation}

\begin{equation}
E(x) = C \int_3^5 x \mathrm{d}x
\end{equation}

\begin{equation}
E(x) = C \Bigg[_3^5 \frac{x^2}{2}
\end{equation}

\begin{equation}
E(x) = C \frac{5^2 - 3^2}{2}
\end{equation}

\begin{equation}
E(x) = C \frac{16}{2}
\end{equation}

\begin{equation}
E(x) = \frac{1}{2}\frac{16}{2} 
\end{equation}

\begin{equation}
E(x) = 4
\end{equation}

And the magic formula for E(x) for a uniform distribution was:
\begin{equation}
E(x) = f(x)\frac{b^2 - a^2}{2}
\end{equation}

However the book says that can be reduced, but here is
my current state:

\begin{equation}
E(x) = \frac{1}{b - a}\frac{b^2 - a^2}{2} = \frac{1}{2}\frac{b^2 - a^2}{b - a}
\end{equation}

So, that second fraction. I don't want to do it. Can emacs do it?

Lets try... typing

'(b^2 - a^2)/(b-a)

and then simplify it with emacs...

I found d B to display it big. That's kind of nice.
Actually:

  * d N : Normal Display
  * d B : Big display
  * d C : C program display
  * d T : TeX program display
  * d L : Latex program display.

So my calculator can actually give me the latex commands I can embed in
this document. That's pretty sweet.  Lets try some algebraic commands:

   1. a s : nope (algebraic simplify)
   2. a = : nope (algebraic solve)
   3. a " : nope (algebraic calc-formula-expand)

Okay, [[https://www.gnu.org/software/emacs/manual/html_mono/calc.html#Simplifying-Formulas][the manual on calc simplification]] says

#+begin_quote
 None of Calc's simplification commands are designed to pull rabbits
 out of hats; they simply apply certain specific rules to put formulas
 into less redundant or more pleasing forms. Serious algebra in Calc
 must be done manually, usually with a combination of selections and
 rewrite rules. See Rearranging with Selections. See Rewrite Rules.
#+end_quote

So the rearrange is 

 * j R : move term right
 * j L : move term left
 * j D : distribute law


And apparently j D is implemented using rewrite rules. Press s e to see those
(and type 'DistribRules'. Press C-c C-c when done, ideally without making changes.

  * j M : undo the distribute (merge)
  * j C : commute (swap a + b + c  ===>  b + a + c)
  * j N : negate
  * j & : invert
  * j E : move term to other side of equals
  * j I : isolate a variable (uses a S to solve for a variable)
  * j * : multiply both sides by a number
  * j + : add to both sides of an equation
  * j - : subtract from both sides of an equation

So lets see if we can derive it ourselves using calc and some hints:
http://www.sosmath.com/tables/algiden/algiden.html

Factoring formulas.

Apparently x^2 - y^2 = (x + y)(x - y)

I wonder if I can put a rewrite rule for this into emacs?

Actually, putting 

' x^2 - y^2 into calc
and typing a f factors it.

I wonder if it can do the cubed ones? Nope.

Hey, cool:

#+begin_example
' (x^2 - y^2) / (x - y)
a f
#+end_example

gives the result: a + b

So emacs *can* do it. And, very likely, as I start to get into more
complex powers, I can probably implement the general factor rule
myself as a rewrite rule. I hate doing math, so this is good.

To sum:

#+begin_example
M-x calc
d B
m f     (fraction mode, don't turn 1/2 into .5)
' (1/2)(b^2 - a^2)/(b - a)
a f
d L
#+end_example

\begin{equation}
E(x) = \frac{1}{2}\frac{b^2 - a^2}{b - a} = \frac{b + a}{2}
\end{equation}

(furthermore, I think I can wrap the above in an emacs 'calc' language block...)

Emacs rocks.
