#+STARTUP: showall indent
#+STARTUP: hidestars
#+TITLE: Variance of a Continuous Uniform Distribution
#+AUTHOR: Warren Wilkinson
#+BEGIN_HTML
---
layout: post
title: Variance of a Continuous Uniform Distribution
excerpt: Using emacs, calc and org-mode to investigate some simple mathematics
categories:
    - emacs
    - statistics
---
#+END_HTML

* First, embedded calc mode.

So [[file:2013-08-11-expectation_of_uniform_continous_distribution.org][last time]] I computed the expected value of a continous uniform distribution. And there I said I wanted
to explore  [[http://www.math.utah.edu/docs/info/calc_17.html][embedded calc mode]] and see if I could get it to print my equations (rather than me typing them).

So lets try: First I'm gonna write my equation in the document like
so:

#+begin_example
# [calc-mode: language: latex]
\begin{equation}
f(x) = x^2 + 1
\end{equation}
#+end_example

Then I'm gonna put my cursor on the equation text (say the =
sign) then press M-# e.  I get 'M-# is undefined'. So I whip
out info (M-x info) lookup Calc, and am told to use C-x * e. 

Now I put my cursor on the equals sign and press 'j - 2 RET' and it
subtracts two from each side giving me:

#+begin_example
\begin{equation}
f(x) -2 = x^2 - 1
\end{equation}
#+end_example

Which is nice, but not what I want. I want to copy the
equation first. *Aha, here it is:* C-x * d (duplicate formula under cursor).
It even copies the surrounding /begin{equation}/ and /end{equation}/,
so that's perfect.


* Variance

Okay, so it's \sigma^2 = (b-a)^2/12. Where does that come from?  

*Given*

\begin{equation}
f(x) = \frac{1}{x_{max} - x_{min}}
\end{equation}

\begin{equation}
P_{ab} = \frac{(b -a)}{(x_{max} - x_{min})}
\end{equation}

\begin{equation}
E(x) = \frac{b + a}{2}
\end{equation}

Also, I've been told:

\begin{equation}
\sigma^2 = E(x^2) - E(x)^2
\end{equation}

But I don't know where that comes from.


** Variance from difference of Expectations

So the variance is the sum of square distances from the mean.

# [calc-mode: language: latex]
\begin{equation}
\sigma^2 = \int_x (x - \mu)^2 P(x)
\end{equation}

a x (expand, cursor on the ^)

\begin{equation}
\sigma^2 = \int_x x^2 P(x) - 2 \int_x \mu x P(x) + \int_x \mu^2 P(x)
\end{equation}

That expanded more than I'd expected, as it also carried the integral sign and the P(x) too. Which was gonna
be my next steps anyway. The last term,

\begin{equation}
\int_x \mu^2 P(x)
\end{equation}

Is equal to just \mu^2, because the area under the Probability density function is equal to 1. 

\begin{equation}
\sigma^2 = \int_x x^2 P(x) - 2 \int_x \mu x P(x) + \mu^2
\end{equation}

The second term, 

\begin{equation}
\int_x \mu x P(x)
\end{equation}

Is going to be mu times the value of x P(x) -- which is the weighted probability, which is just the expectation \mu again.


\begin{equation}
\sigma^2 = \int_x x^2 P(x) - 2 \mu^2 + \mu^2
\end{equation}

And that simplifies too

\begin{equation}
\sigma^2 = \int_x x^2 P(x) - \mu^2
\end{equation}

So I guess what we are saying is that 

\begin{equation}
E(x^2) = \int_x x^2 P(x) 
\end{equation}

Which is a strange formula for me, because P(x) has stayed P(x) and didn't become P(x^2). I guess that's why, in wikipedia they wrote it
as 

\begin{equation}
P(X = x) 
\end{equation}

Which I'll do as well from now on, to show that this is what we're talking about. Interesting idea anyway. Glad to know it.

* Variance of uniform distribution

Now, using

# [calc-mode: language: latex]
\begin{equation}
\sigma^2 = E(x^2) - E(x)^2
\end{equation}

\begin{equation}
\sigma^2 = \int x^2 P(X = x) - \frac{a+b}{2}^2
\end{equation}

\begin{equation}
\sigma^{2} = \int x^{2} P\left( X = x \right) - \frac{(a + b)^{2}}{4}
\end{equation}

\begin{equation}
\sigma^{2} = \int x^{2} P\left( X = x \right) - \frac{b^{2} + 2 a b + a^{2}}{4}
\end{equation}

Since P(x = X) is 1/(b - a)

\begin{equation}
\sigma^2 = \int \frac{x^2}{b-a} - \frac{b^2 + 2 a b + a^2}{4}
\end{equation}

\begin{equation}
\sigma^2 = \Bigg [_{a}^{b}\frac{x^3}{3(b - a)} - \frac{b^2 + 2 a b + a^2}{4}
\end{equation}

\begin{equation}
\sigma^2 = \frac{b^3 - a^3}{3(b - a)} - \frac{b^2 + 2 a b + a^2}{4}
\end{equation}

j s to select it the first term, a n to normalize ?? 

\begin{equation}
\sigma^{2} = \frac{b^{2} + a b + a^{2}}{3} - \frac{b^{2} + 2 a b + a^{2}}{4}
\end{equation}

then a f (calc factor) 

\begin{equation}
12 \sigma^2 = (b - a)^2
\end{equation}

Then j / 12 (divide both sides by twelve)

\begin{equation}
\sigma^2 = \frac{(b - a)^2}{12}
\end{equation}

And there we have it.  So the math is right, I'm just not entirely sure
how calc did it.  It's nice that it did though.


