#+STARTUP: showall indent
#+STARTUP: hidestars
#+TITLE: Old Projects
#+OPTIONS: ^:nil, TeX:nil
#+AUTHOR: Warren Wilkinson
#+BEGIN_HTML
---
layout: post
title: Old Projects, House keeping, good intentions
excerpt: Just mentioning an old project I never have time to touch upon
categories:
    - lisp
    - programming
---
#+END_HTML

* Too Much Organization

I closed by corporate BitBucket account today. BitBucket is a wonderful service.
I had planned to do a lot with it; but I never got around to it.

For a while, I'd setup gerrit and jenkins. And I had this big corporate repository,
that contained every git project as a subproject.  Everything was going to be
perfection.

But that never came to pass. I guess I made it too hard to develop,
and I ran out of steam.

* Simplifications

Instead, I took the one project I really, really, want to one day support (lispdb)
and put it up as it's own repository.  No more subprojects, gerrit or jenkins.

Most of the rest of the code I found I didn't really need or want.  For example,
I once had a ton of Emacs customizations, in a git repository.

Then, I deleted that and went with [[https://github.com/bbatsov/prelude][Prelude Emacs]].  But that didn't work well with
my Prolog mode, and I found some of it's key bindings frustrating.

I deleted that and rewrote my .emacs file:  It's now 180 loc.  Most of it is in
the form custom-set-variables, configuration for this blog, and configuration for
email. I don't get lost anymore.

* Lisp DB?

Lisp DB is my itch... one of them.  It came from a former solo-startup of mine that
tanked.

It's a database. Entirely in lisp. Based upon b*trees.  It has a number of neato
features:

  * Acid Compliant
  * Multi-threaded and thread safe
  * Extremely fast
  * Schema-less
  * Store data of arbitrary size.

It's also cool in that I used it as both data store and file system.  When clients
uploaded data, the attachments were stored in with the data.  The whole thing
was based of some Amiga transactional file system, whose name I don't remember.

Anyway, that's just one I'd like to get something out of. Release it, even if nobody
uses it, just to say "THERE, THAT'S DONE."

It's not alone. I've got a nutrition parser in Prolog, A provably correct rewrite of
curlftpfs, and a partially done ACL2 tutorial, and a Math Masters degree to get.

One day.
